//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answers
    {
        public int ID { get; set; }
        public int QuestionID { get; set; }
        public int AnswerValue { get; set; }
    
        public virtual Questions Questions { get; set; }
    }
}
